2025-10-12 17:59:58,793 - gateway - ERROR - Error setting up local broker (attempt 1): [Errno 2] No such file or directory
2025-10-12 18:00:03,999 - gateway - ERROR - Error setting up local broker (attempt 2): [Errno 2] No such file or directory
2025-10-12 18:00:09,209 - gateway - ERROR - Error setting up local broker (attempt 3): [Errno 2] No such file or directory
2025-10-12 18:00:09,210 - gateway - CRITICAL - Failed to connect to local MQTT broker after all retries
2025-10-12 18:00:46,030 - gateway - ERROR - Error setting up local broker (attempt 1): [Errno 2] No such file or directory
2025-10-12 18:01:47,599 - gateway - ERROR - Error setting up local broker (attempt 1): [Errno 2] No such file or directory
2025-10-12 18:01:52,803 - gateway - ERROR - Error setting up local broker (attempt 2): [Errno 2] No such file or directory
2025-10-12 18:02:47,373 - gateway - INFO - Local MQTT broker connected successfully
2025-10-12 18:02:47,373 - gateway - INFO - Connected to local MQTT broker
2025-10-12 18:02:48,297 - gateway - INFO - AWS MQTT connected successfully
2025-10-12 18:02:48,298 - gateway - ERROR - LoRa connection failed: could not open port 'COM5': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)
2025-10-12 18:02:48,298 - gateway - INFO - Gateway started
2025-10-12 18:02:48,975 - gateway - INFO - Connected to AWS IoT
2025-10-12 18:04:07,057 - gateway - INFO - Shutting down gateway...
2025-10-12 18:04:07,058 - gateway - INFO - Cleaning up connections...
2025-10-12 18:04:08,688 - gateway - INFO - Gateway stopped
2025-10-12 18:25:28,801 - gateway - INFO - Local MQTT broker connected successfully
2025-10-12 18:25:28,801 - gateway - INFO - Connected to local MQTT broker
2025-10-12 18:25:29,911 - gateway - INFO - AWS MQTT connected successfully
2025-10-12 18:25:29,911 - gateway - ERROR - LoRa connection failed: could not open port 'COM5': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)
2025-10-12 18:25:29,911 - gateway - INFO - Gateway started
2025-10-12 18:25:30,595 - gateway - INFO - Connected to AWS IoT
2025-10-12 18:27:36,202 - gateway - WARNING - Local MQTT disconnected unexpectedly (rc=7), reconnecting...
2025-10-12 18:30:34,222 - gateway - INFO - Shutting down gateway...
2025-10-12 18:30:34,223 - gateway - INFO - Cleaning up connections...
2025-10-12 18:30:35,773 - gateway - INFO - Gateway stopped
2025-10-12 18:30:37,207 - gateway - INFO - Local MQTT broker connected successfully
2025-10-12 18:30:37,209 - gateway - INFO - Connected to local MQTT broker
2025-10-12 18:30:38,018 - gateway - INFO - AWS MQTT connected successfully
2025-10-12 18:30:38,018 - gateway - ERROR - LoRa connection failed: could not open port 'COM5': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)
2025-10-12 18:30:38,018 - gateway - INFO - Gateway started
2025-10-12 18:30:38,654 - gateway - INFO - Connected to AWS IoT
2025-10-12 18:33:47,156 - gateway - WARNING - Local MQTT disconnected unexpectedly (rc=7), reconnecting...
2025-10-12 18:33:53,192 - gateway - INFO - Connected to local MQTT broker
2025-10-12 18:36:56,573 - gateway - INFO - Shutting down gateway...
2025-10-12 18:36:56,573 - gateway - INFO - Cleaning up connections...
2025-10-12 18:36:57,939 - gateway - INFO - Gateway stopped
2025-10-12 18:37:01,002 - gateway - INFO - Local MQTT broker connected successfully
2025-10-12 18:37:01,002 - gateway - INFO - Connected to local MQTT broker
2025-10-12 18:37:02,265 - gateway - INFO - AWS MQTT connected successfully
2025-10-12 18:37:02,265 - gateway - ERROR - LoRa connection failed: could not open port 'COM5': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)
2025-10-12 18:37:02,272 - gateway - INFO - Gateway started
2025-10-12 18:37:02,980 - gateway - INFO - Connected to AWS IoT
2025-10-12 18:43:34,826 - gateway - INFO - Shutting down gateway...
2025-10-12 18:43:34,827 - gateway - INFO - Cleaning up connections...
2025-10-12 18:43:35,188 - gateway - INFO - Gateway stopped
2025-10-12 18:43:36,964 - gateway - INFO - Local MQTT broker connected successfully
2025-10-12 18:43:36,964 - gateway - INFO - Connected to local MQTT broker
2025-10-12 18:43:37,768 - gateway - INFO - AWS MQTT connected successfully
2025-10-12 18:43:37,768 - gateway - ERROR - LoRa connection failed: could not open port 'COM5': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)
2025-10-12 18:43:37,768 - gateway - INFO - Gateway started
2025-10-12 18:43:38,414 - gateway - INFO - Connected to AWS IoT
2025-10-12 18:47:13,876 - gateway - WARNING - Local MQTT disconnected unexpectedly (rc=7), reconnecting...
2025-10-12 18:47:19,912 - gateway - INFO - Connected to local MQTT broker
2025-10-12 18:47:36,101 - gateway - INFO - Shutting down gateway...
2025-10-12 18:47:36,101 - gateway - INFO - Cleaning up connections...
2025-10-12 18:47:37,869 - gateway - INFO - Gateway stopped
2025-10-12 18:49:37,501 - gateway - INFO - Local MQTT broker connected successfully
2025-10-12 18:49:37,501 - gateway - INFO - Connected to local MQTT broker
2025-10-12 18:49:39,089 - gateway - INFO - AWS MQTT connected successfully
2025-10-12 18:49:39,090 - gateway - ERROR - LoRa connection failed: could not open port 'COM5': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)
2025-10-12 18:49:39,090 - gateway - INFO - Gateway started
2025-10-12 18:49:39,727 - gateway - INFO - Connected to AWS IoT
2025-10-12 18:50:55,866 - gateway - WARNING - Local MQTT disconnected unexpectedly (rc=7), reconnecting...
2025-10-12 18:51:39,308 - gateway - INFO - Shutting down gateway...
2025-10-12 18:51:39,309 - gateway - INFO - Cleaning up connections...
2025-10-12 18:51:40,402 - gateway - INFO - Gateway stopped
2025-10-12 18:51:43,479 - gateway - ERROR - Error setting up local broker (attempt 1): 'gateway_cert'
2025-10-12 18:51:48,664 - gateway - ERROR - Error setting up local broker (attempt 2): 'gateway_cert'
2025-10-12 18:51:53,858 - gateway - ERROR - Error setting up local broker (attempt 3): 'gateway_cert'
2025-10-12 18:51:53,858 - gateway - CRITICAL - Failed to connect to local MQTT broker after all retries
2025-10-12 18:51:54,637 - gateway - INFO - AWS MQTT connected successfully
2025-10-12 18:51:54,637 - gateway - ERROR - LoRa connection failed: could not open port 'COM5': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)
2025-10-12 18:51:54,637 - gateway - INFO - Gateway started
2025-10-12 18:51:55,295 - gateway - INFO - Connected to AWS IoT
2025-10-12 18:51:55,638 - gateway - INFO - Shutting down gateway...
2025-10-12 18:51:55,638 - gateway - INFO - Cleaning up connections...
2025-10-12 18:51:56,595 - gateway - INFO - Gateway stopped
2025-10-12 18:53:08,822 - gateway - ERROR - Error setting up local broker (attempt 1): [WinError 10061] No connection could be made because the target machine actively refused it
2025-10-12 18:53:16,054 - gateway - ERROR - Error setting up local broker (attempt 2): [WinError 10061] No connection could be made because the target machine actively refused it
2025-10-12 18:53:21,271 - gateway - INFO - Local MQTT broker connected successfully
2025-10-12 18:53:21,271 - gateway - INFO - Connected to local MQTT broker
2025-10-12 18:53:22,129 - gateway - INFO - AWS MQTT connected successfully
2025-10-12 18:53:22,129 - gateway - ERROR - LoRa connection failed: could not open port 'COM5': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)
2025-10-12 18:53:22,129 - gateway - INFO - Gateway started
2025-10-12 18:53:22,772 - gateway - INFO - Connected to AWS IoT
2025-10-12 18:53:49,133 - gateway - WARNING - Local MQTT disconnected unexpectedly (rc=7), reconnecting...
2025-10-12 18:54:59,850 - gateway - INFO - Shutting down gateway...
2025-10-12 18:54:59,850 - gateway - INFO - Cleaning up connections...
2025-10-12 18:55:00,930 - gateway - INFO - Gateway stopped
2025-10-12 18:55:06,561 - gateway - INFO - Local MQTT broker connected successfully
2025-10-12 18:55:06,561 - gateway - INFO - Connected to local MQTT broker
2025-10-12 18:55:07,321 - gateway - INFO - AWS MQTT connected successfully
2025-10-12 18:55:07,322 - gateway - ERROR - LoRa connection failed: could not open port 'COM5': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)
2025-10-12 18:55:07,322 - gateway - INFO - Gateway started
2025-10-12 18:55:07,946 - gateway - INFO - Connected to AWS IoT
2025-10-12 18:55:25,124 - gateway - INFO - Request from passkey_01: {'body': '{"cmd":"unlock_request","client_id":"passkey_01","pw":"064b1b97b8762e109f8280fd47bb5c5ab33adca5a7f7231aef22b23ce31fbfa4","ts":1760270123,"nonce":1392790571}', 'hmac': 'bd7a9b6d1689391f194240fcb600451f2050952ac5c186f0877ca1712769906e'}
2025-10-12 18:55:25,124 - gateway - WARNING - No matching password found
2025-10-12 18:55:25,124 - gateway - WARNING - Access denied: invalid_password
2025-10-12 18:57:11,905 - gateway - INFO - Shutting down gateway...
2025-10-12 18:57:11,905 - gateway - INFO - Cleaning up connections...
2025-10-12 18:57:13,655 - gateway - INFO - Gateway stopped
2025-10-12 18:57:14,898 - gateway - INFO - Local MQTT broker connected successfully
2025-10-12 18:57:14,899 - gateway - INFO - Connected to local MQTT broker
2025-10-12 18:57:14,916 - gateway - ERROR - Failed to publish to AWS: 4
2025-10-12 18:57:15,772 - gateway - INFO - AWS MQTT connected successfully
2025-10-12 18:57:15,772 - gateway - ERROR - LoRa connection failed: could not open port 'COM5': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)
2025-10-12 18:57:15,773 - gateway - INFO - Gateway started
2025-10-12 18:57:16,398 - gateway - INFO - Connected to AWS IoT
2025-10-12 18:57:24,232 - gateway - INFO - Request from passkey_01: {'body': '{"cmd":"unlock_request","client_id":"passkey_01","pw":"064b1b97b8762e109f8280fd47bb5c5ab33adca5a7f7231aef22b23ce31fbfa4","ts":1760270242,"nonce":78819671}', 'hmac': '60df8edda43ba9aa6760e751d051ba5a460a9fd4fc69c3ef293b8637c0ab37c6'}
2025-10-12 18:57:24,232 - gateway - INFO - Password authenticated: user_001
2025-10-12 18:57:24,234 - gateway - INFO - Access granted for password ID: user_001
2025-10-12 18:57:35,308 - gateway - WARNING - Local MQTT disconnected unexpectedly (rc=7), reconnecting...
2025-10-12 18:57:35,964 - gateway - INFO - Shutting down gateway...
2025-10-12 18:57:35,964 - gateway - INFO - Cleaning up connections...
2025-10-12 18:57:41,152 - gateway - INFO - Gateway stopped
2025-10-12 19:01:49,685 - gateway - ERROR - Error setting up local broker (attempt 1): [WinError 10061] No connection could be made because the target machine actively refused it
2025-10-12 19:01:54,911 - gateway - INFO - Local MQTT broker connected successfully
2025-10-12 19:01:54,911 - gateway - INFO - Connected to local MQTT broker
2025-10-12 19:01:56,215 - gateway - INFO - AWS MQTT connected successfully
2025-10-12 19:01:56,215 - gateway - ERROR - LoRa connection failed: could not open port 'COM5': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)
2025-10-12 19:01:56,217 - gateway - INFO - Gateway started
2025-10-12 19:01:56,824 - gateway - INFO - Connected to AWS IoT
2025-10-12 19:02:30,416 - gateway - INFO - Shutting down gateway...
2025-10-12 19:02:30,416 - gateway - INFO - Cleaning up connections...
2025-10-12 19:02:31,292 - gateway - INFO - Gateway stopped
2025-10-12 19:02:32,508 - gateway - INFO - Local MQTT broker connected successfully
2025-10-12 19:02:32,508 - gateway - INFO - Connected to local MQTT broker
2025-10-12 19:02:33,491 - gateway - INFO - AWS MQTT connected successfully
2025-10-12 19:02:33,500 - gateway - INFO - LoRa connected on COM5
2025-10-12 19:02:33,500 - gateway - INFO - Gateway started
2025-10-12 19:02:34,058 - gateway - INFO - Connected to AWS IoT
2025-10-12 19:14:14,637 - gateway - INFO - Shutting down gateway...
2025-10-12 19:14:14,637 - gateway - INFO - Cleaning up connections...
2025-10-12 19:14:15,179 - gateway - INFO - Gateway stopped
2025-10-12 19:14:27,534 - gateway - INFO - Local MQTT broker connected successfully
2025-10-12 19:14:27,534 - gateway - INFO - Connected to local MQTT broker
2025-10-12 19:14:28,395 - gateway - INFO - AWS MQTT connected successfully
2025-10-12 19:14:28,461 - gateway - INFO - LoRa connected on COM5
2025-10-12 19:14:28,464 - gateway - INFO - Gateway started
2025-10-12 19:14:28,987 - gateway - INFO - Connected to AWS IoT
2025-10-12 19:18:11,898 - gateway - ERROR - Gateway error: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
Traceback (most recent call last):
  File "P:\MMT\__IoT\First_IoT\Gateway\main.py", line 935, in run
    if self.serial_conn and self.serial_conn.in_waiting > 0:
  File "D:\Miniconda3\envs\IoT\lib\site-packages\serial\serialwin32.py", line 259, in in_waiting
    raise SerialException("ClearCommError failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
2025-10-12 19:18:12,921 - gateway - ERROR - Gateway error: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
Traceback (most recent call last):
  File "P:\MMT\__IoT\First_IoT\Gateway\main.py", line 935, in run
    if self.serial_conn and self.serial_conn.in_waiting > 0:
  File "D:\Miniconda3\envs\IoT\lib\site-packages\serial\serialwin32.py", line 259, in in_waiting
    raise SerialException("ClearCommError failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
2025-10-12 19:18:13,922 - gateway - ERROR - Gateway error: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
Traceback (most recent call last):
  File "P:\MMT\__IoT\First_IoT\Gateway\main.py", line 935, in run
    if self.serial_conn and self.serial_conn.in_waiting > 0:
  File "D:\Miniconda3\envs\IoT\lib\site-packages\serial\serialwin32.py", line 259, in in_waiting
    raise SerialException("ClearCommError failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
2025-10-12 19:18:14,924 - gateway - ERROR - Gateway error: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
Traceback (most recent call last):
  File "P:\MMT\__IoT\First_IoT\Gateway\main.py", line 935, in run
    if self.serial_conn and self.serial_conn.in_waiting > 0:
  File "D:\Miniconda3\envs\IoT\lib\site-packages\serial\serialwin32.py", line 259, in in_waiting
    raise SerialException("ClearCommError failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
2025-10-12 19:18:15,930 - gateway - ERROR - Gateway error: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
Traceback (most recent call last):
  File "P:\MMT\__IoT\First_IoT\Gateway\main.py", line 935, in run
    if self.serial_conn and self.serial_conn.in_waiting > 0:
  File "D:\Miniconda3\envs\IoT\lib\site-packages\serial\serialwin32.py", line 259, in in_waiting
    raise SerialException("ClearCommError failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
2025-10-12 19:18:16,940 - gateway - ERROR - Gateway error: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
Traceback (most recent call last):
  File "P:\MMT\__IoT\First_IoT\Gateway\main.py", line 935, in run
    if self.serial_conn and self.serial_conn.in_waiting > 0:
  File "D:\Miniconda3\envs\IoT\lib\site-packages\serial\serialwin32.py", line 259, in in_waiting
    raise SerialException("ClearCommError failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
2025-10-12 19:18:17,952 - gateway - ERROR - Gateway error: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
Traceback (most recent call last):
  File "P:\MMT\__IoT\First_IoT\Gateway\main.py", line 935, in run
    if self.serial_conn and self.serial_conn.in_waiting > 0:
  File "D:\Miniconda3\envs\IoT\lib\site-packages\serial\serialwin32.py", line 259, in in_waiting
    raise SerialException("ClearCommError failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
2025-10-12 19:18:18,954 - gateway - ERROR - Gateway error: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
Traceback (most recent call last):
  File "P:\MMT\__IoT\First_IoT\Gateway\main.py", line 935, in run
    if self.serial_conn and self.serial_conn.in_waiting > 0:
  File "D:\Miniconda3\envs\IoT\lib\site-packages\serial\serialwin32.py", line 259, in in_waiting
    raise SerialException("ClearCommError failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
2025-10-12 19:18:19,967 - gateway - ERROR - Gateway error: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
Traceback (most recent call last):
  File "P:\MMT\__IoT\First_IoT\Gateway\main.py", line 935, in run
    if self.serial_conn and self.serial_conn.in_waiting > 0:
  File "D:\Miniconda3\envs\IoT\lib\site-packages\serial\serialwin32.py", line 259, in in_waiting
    raise SerialException("ClearCommError failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
2025-10-12 19:18:20,970 - gateway - ERROR - Gateway error: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
Traceback (most recent call last):
  File "P:\MMT\__IoT\First_IoT\Gateway\main.py", line 935, in run
    if self.serial_conn and self.serial_conn.in_waiting > 0:
  File "D:\Miniconda3\envs\IoT\lib\site-packages\serial\serialwin32.py", line 259, in in_waiting
    raise SerialException("ClearCommError failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
2025-10-12 19:18:21,983 - gateway - ERROR - Gateway error: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
Traceback (most recent call last):
  File "P:\MMT\__IoT\First_IoT\Gateway\main.py", line 935, in run
    if self.serial_conn and self.serial_conn.in_waiting > 0:
  File "D:\Miniconda3\envs\IoT\lib\site-packages\serial\serialwin32.py", line 259, in in_waiting
    raise SerialException("ClearCommError failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
2025-10-12 19:18:22,991 - gateway - ERROR - Gateway error: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
Traceback (most recent call last):
  File "P:\MMT\__IoT\First_IoT\Gateway\main.py", line 935, in run
    if self.serial_conn and self.serial_conn.in_waiting > 0:
  File "D:\Miniconda3\envs\IoT\lib\site-packages\serial\serialwin32.py", line 259, in in_waiting
    raise SerialException("ClearCommError failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
2025-10-12 19:18:23,994 - gateway - ERROR - Gateway error: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
Traceback (most recent call last):
  File "P:\MMT\__IoT\First_IoT\Gateway\main.py", line 935, in run
    if self.serial_conn and self.serial_conn.in_waiting > 0:
  File "D:\Miniconda3\envs\IoT\lib\site-packages\serial\serialwin32.py", line 259, in in_waiting
    raise SerialException("ClearCommError failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
2025-10-12 19:18:25,010 - gateway - ERROR - Gateway error: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
Traceback (most recent call last):
  File "P:\MMT\__IoT\First_IoT\Gateway\main.py", line 935, in run
    if self.serial_conn and self.serial_conn.in_waiting > 0:
  File "D:\Miniconda3\envs\IoT\lib\site-packages\serial\serialwin32.py", line 259, in in_waiting
    raise SerialException("ClearCommError failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
2025-10-12 19:18:26,010 - gateway - ERROR - Gateway error: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
Traceback (most recent call last):
  File "P:\MMT\__IoT\First_IoT\Gateway\main.py", line 935, in run
    if self.serial_conn and self.serial_conn.in_waiting > 0:
  File "D:\Miniconda3\envs\IoT\lib\site-packages\serial\serialwin32.py", line 259, in in_waiting
    raise SerialException("ClearCommError failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
2025-10-12 19:18:27,016 - gateway - ERROR - Gateway error: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
Traceback (most recent call last):
  File "P:\MMT\__IoT\First_IoT\Gateway\main.py", line 935, in run
    if self.serial_conn and self.serial_conn.in_waiting > 0:
  File "D:\Miniconda3\envs\IoT\lib\site-packages\serial\serialwin32.py", line 259, in in_waiting
    raise SerialException("ClearCommError failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
2025-10-12 19:18:28,019 - gateway - ERROR - Gateway error: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
Traceback (most recent call last):
  File "P:\MMT\__IoT\First_IoT\Gateway\main.py", line 935, in run
    if self.serial_conn and self.serial_conn.in_waiting > 0:
  File "D:\Miniconda3\envs\IoT\lib\site-packages\serial\serialwin32.py", line 259, in in_waiting
    raise SerialException("ClearCommError failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
2025-10-12 19:18:29,033 - gateway - ERROR - Gateway error: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
Traceback (most recent call last):
  File "P:\MMT\__IoT\First_IoT\Gateway\main.py", line 935, in run
    if self.serial_conn and self.serial_conn.in_waiting > 0:
  File "D:\Miniconda3\envs\IoT\lib\site-packages\serial\serialwin32.py", line 259, in in_waiting
    raise SerialException("ClearCommError failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
2025-10-12 19:18:33,542 - gateway - INFO - Local MQTT broker connected successfully
2025-10-12 19:18:33,542 - gateway - INFO - Connected to local MQTT broker
2025-10-12 19:18:34,396 - gateway - INFO - AWS MQTT connected successfully
2025-10-12 19:18:34,462 - gateway - INFO - LoRa connected on COM5
2025-10-12 19:18:34,462 - gateway - INFO - Gateway started
2025-10-12 19:18:34,995 - gateway - INFO - Connected to AWS IoT
2025-10-12 19:27:57,349 - gateway - ERROR - Gateway error: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
Traceback (most recent call last):
  File "P:\MMT\__IoT\First_IoT\Gateway\main.py", line 935, in run
  File "D:\Miniconda3\envs\IoT\lib\site-packages\serial\serialwin32.py", line 259, in in_waiting
    raise SerialException("ClearCommError failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
2025-10-12 19:27:58,366 - gateway - ERROR - Gateway error: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
Traceback (most recent call last):
  File "P:\MMT\__IoT\First_IoT\Gateway\main.py", line 935, in run
  File "D:\Miniconda3\envs\IoT\lib\site-packages\serial\serialwin32.py", line 259, in in_waiting
    raise SerialException("ClearCommError failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
2025-10-12 19:27:59,367 - gateway - ERROR - Gateway error: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
Traceback (most recent call last):
  File "P:\MMT\__IoT\First_IoT\Gateway\main.py", line 935, in run
  File "D:\Miniconda3\envs\IoT\lib\site-packages\serial\serialwin32.py", line 259, in in_waiting
    raise SerialException("ClearCommError failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
2025-10-12 19:28:00,375 - gateway - ERROR - Gateway error: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
Traceback (most recent call last):
  File "P:\MMT\__IoT\First_IoT\Gateway\main.py", line 935, in run
  File "D:\Miniconda3\envs\IoT\lib\site-packages\serial\serialwin32.py", line 259, in in_waiting
    raise SerialException("ClearCommError failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
2025-10-12 19:28:01,379 - gateway - ERROR - Gateway error: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
Traceback (most recent call last):
  File "P:\MMT\__IoT\First_IoT\Gateway\main.py", line 935, in run
  File "D:\Miniconda3\envs\IoT\lib\site-packages\serial\serialwin32.py", line 259, in in_waiting
    raise SerialException("ClearCommError failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
2025-10-12 19:28:02,396 - gateway - ERROR - Gateway error: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
Traceback (most recent call last):
  File "P:\MMT\__IoT\First_IoT\Gateway\main.py", line 935, in run
  File "D:\Miniconda3\envs\IoT\lib\site-packages\serial\serialwin32.py", line 259, in in_waiting
    raise SerialException("ClearCommError failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
2025-10-12 19:28:03,403 - gateway - ERROR - Gateway error: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
Traceback (most recent call last):
  File "P:\MMT\__IoT\First_IoT\Gateway\main.py", line 935, in run
  File "D:\Miniconda3\envs\IoT\lib\site-packages\serial\serialwin32.py", line 259, in in_waiting
    raise SerialException("ClearCommError failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
2025-10-12 22:26:26,773 - gateway - INFO - Local MQTT broker connected successfully
2025-10-12 22:26:26,773 - gateway - INFO - Connected to local MQTT broker
2025-10-12 22:26:27,729 - gateway - INFO - AWS MQTT connected successfully
2025-10-12 22:26:27,729 - gateway - ERROR - LoRa connection failed: could not open port 'COM5': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)
2025-10-12 22:26:27,729 - gateway - INFO - Gateway started
2025-10-12 22:26:29,855 - gateway - INFO - Connected to AWS IoT
2025-10-12 22:26:56,666 - gateway - WARNING - Local MQTT disconnected unexpectedly (rc=7), reconnecting...
2025-10-12 22:27:02,697 - gateway - INFO - Connected to local MQTT broker
2025-10-12 22:30:41,705 - gateway - WARNING - Local MQTT disconnected unexpectedly (rc=7), reconnecting...
2025-10-12 22:31:25,837 - gateway - INFO - Connected to local MQTT broker
2025-10-12 22:34:23,665 - gateway - WARNING - Local MQTT disconnected unexpectedly (rc=7), reconnecting...
2025-10-12 22:34:33,711 - gateway - INFO - Connected to local MQTT broker
2025-10-12 22:35:03,898 - gateway - WARNING - Local MQTT disconnected unexpectedly (rc=7), reconnecting...
2025-10-12 22:38:08,439 - gateway - INFO - Shutting down gateway...
2025-10-12 22:38:08,444 - gateway - INFO - Cleaning up connections...
2025-10-12 22:38:08,801 - gateway - INFO - Gateway stopped
2025-10-12 22:38:09,970 - gateway - INFO - Local MQTT broker connected successfully
2025-10-12 22:38:09,974 - gateway - INFO - Connected to local MQTT broker
2025-10-12 22:38:09,992 - gateway - ERROR - Failed to publish to AWS: 4
2025-10-12 22:38:10,875 - gateway - ERROR - Failed to publish to AWS: 4
2025-10-12 22:38:10,892 - gateway - INFO - AWS MQTT connected successfully
2025-10-12 22:38:10,893 - gateway - ERROR - LoRa connection failed: could not open port 'COM5': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)
2025-10-12 22:38:10,893 - gateway - INFO - Gateway started
2025-10-12 22:38:11,534 - gateway - INFO - Connected to AWS IoT
2025-10-12 22:40:06,011 - gateway - INFO - Command sent to fan_01: {'cmd': 'fan_on'}
2025-10-12 22:40:24,543 - gateway - WARNING - Local MQTT disconnected unexpectedly (rc=7), reconnecting...
2025-10-12 22:40:25,175 - gateway - INFO - Shutting down gateway...
2025-10-12 22:40:25,176 - gateway - INFO - Cleaning up connections...
2025-10-12 22:40:29,602 - gateway - INFO - Gateway stopped
2025-10-13 15:12:09,314 - gateway - ERROR - ============================================================
2025-10-13 15:12:09,354 - gateway - ERROR -    - Local CA: ./broker_cert/ca.cert.pem
2025-10-13 15:12:09,356 - gateway - ERROR -    - VPS CA: ./vps_certs/ca.crt
2025-10-13 15:12:09,356 - gateway - ERROR -    - VPS Cert: ./vps_certs/gateway.crt
2025-10-13 15:12:09,356 - gateway - ERROR -    - VPS Key: ./vps_certs/gateway.key
2025-10-13 15:12:09,356 - gateway - ERROR - 
2025-10-13 15:12:09,357 - gateway - ERROR - Please follow setup guide to create/download certificates
2025-10-13 15:12:09,357 - gateway - ERROR - ============================================================
2025-10-13 15:13:39,337 - gateway - INFO - Setting up Local MQTT Broker...
2025-10-13 15:13:39,660 - gateway - INFO - Setting up VPS MQTT...
2025-10-13 15:13:42,406 - gateway - ERROR - VPS MQTT connection failed: [Errno 11001] getaddrinfo failed
2025-10-13 15:13:42,408 - gateway - ERROR - LoRa connection failed: could not open port 'COM5': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)
2025-10-13 15:13:42,408 - gateway - INFO - ============================================================
2025-10-13 15:13:42,408 - gateway - INFO - Local MQTT: 192.168.1.148:1884
2025-10-13 15:13:42,408 - gateway - INFO - VPS MQTT: YOUR_VPS_IP:8883
2025-10-13 15:13:42,410 - gateway - INFO - ============================================================
2025-10-13 15:13:49,030 - gateway - INFO - Cleaning up connections...
2025-10-13 15:13:49,802 - gateway - INFO - Cleaning up connections...
2025-10-13 15:20:48,726 - gateway - INFO - Setting up Local MQTT Broker...
2025-10-13 15:20:50,989 - gateway - ERROR - Local MQTT connection failed: [WinError 10061] No connection could be made because the target machine actively refused it
2025-10-13 15:20:50,989 - gateway - INFO - Setting up VPS MQTT...
2025-10-13 15:20:56,005 - gateway - ERROR - VPS MQTT connection failed: timed out
2025-10-13 15:20:56,005 - gateway - ERROR - LoRa connection failed: could not open port 'COM5': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)
2025-10-13 15:20:56,005 - gateway - INFO - ============================================================
2025-10-13 15:20:56,005 - gateway - INFO - Gateway started successfully
2025-10-13 15:20:56,005 - gateway - INFO - Local MQTT: 192.168.1.148:1884
2025-10-13 15:20:56,005 - gateway - INFO - VPS MQTT: 128.199.137.3:8883
2025-10-13 15:20:56,005 - gateway - INFO - ============================================================
2025-10-13 15:21:08,554 - gateway - INFO - 
Shutting down...
2025-10-13 15:21:08,554 - gateway - INFO - Cleaning up connections...
2025-10-13 15:21:08,554 - gateway - INFO - Gateway stopped
2025-10-13 15:21:08,554 - gateway - INFO - Cleaning up connections...
2025-10-13 15:21:08,554 - gateway - INFO - Gateway stopped
2025-10-13 15:21:11,892 - gateway - INFO - Setting up Local MQTT Broker...
2025-10-13 15:21:12,096 - gateway - INFO - Setting up VPS MQTT...
2025-10-13 15:21:17,108 - gateway - ERROR - VPS MQTT connection failed: timed out
2025-10-13 15:21:17,108 - gateway - ERROR - LoRa connection failed: could not open port 'COM5': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)
2025-10-13 15:21:17,108 - gateway - INFO - ============================================================
2025-10-13 15:21:17,108 - gateway - INFO - Gateway started successfully
2025-10-13 15:21:17,108 - gateway - INFO - Local MQTT: 192.168.1.148:1884
2025-10-13 15:21:17,108 - gateway - INFO - VPS MQTT: 128.199.137.3:8883
2025-10-13 15:21:17,108 - gateway - INFO - ============================================================
2025-10-13 15:22:17,149 - gateway - INFO - Stats - RX: 0, TX: 0, Buffered: 0, Local: OK, VPS: OK
2025-10-13 15:23:17,245 - gateway - INFO - Stats - RX: 0, TX: 0, Buffered: 0, Local: OK, VPS: OK
2025-10-13 15:24:17,296 - gateway - INFO - Stats - RX: 0, TX: 0, Buffered: 0, Local: OK, VPS: OK
2025-10-13 15:25:17,397 - gateway - INFO - Stats - RX: 0, TX: 0, Buffered: 0, Local: OK, VPS: OK
2025-10-13 15:26:17,436 - gateway - INFO - Stats - RX: 0, TX: 0, Buffered: 0, Local: OK, VPS: OK
2025-10-13 15:26:49,341 - gateway - INFO - 
Shutting down...
2025-10-13 15:26:49,341 - gateway - INFO - Cleaning up connections...
2025-10-13 15:26:49,484 - gateway - INFO - Gateway stopped
2025-10-13 15:26:49,484 - gateway - INFO - Cleaning up connections...
2025-10-13 15:26:49,484 - gateway - INFO - Gateway stopped
2025-10-13 15:37:21,754 - gateway - INFO - Setting up Local MQTT Broker...
2025-10-13 15:37:21,966 - gateway - INFO - Setting up VPS MQTT...
2025-10-13 15:37:21,966 - gateway - INFO -  Connected to Local MQTT
2025-10-13 15:37:21,970 - gateway - INFO -  Subscribed to local topics
2025-10-13 15:37:21,973 - gateway - INFO -  VPS mTLS configured
2025-10-13 15:37:26,977 - gateway - ERROR - VPS MQTT connection failed: timed out
2025-10-13 15:37:27,045 - gateway - INFO -  LoRa connected on COM5
2025-10-13 15:37:27,045 - gateway - INFO - ============================================================
2025-10-13 15:37:27,045 - gateway - INFO - Gateway started successfully
2025-10-13 15:37:27,045 - gateway - INFO - Local MQTT: 192.168.1.148:1884
2025-10-13 15:37:27,045 - gateway - INFO - VPS MQTT: 128.199.137.3:8883
2025-10-13 15:37:27,047 - gateway - INFO - ============================================================
2025-10-13 15:38:27,081 - gateway - INFO - Stats - RX: 0, TX: 0, Buffered: 0, Local: OK, VPS: OK
2025-10-13 15:39:27,166 - gateway - INFO - Stats - RX: 0, TX: 0, Buffered: 0, Local: OK, VPS: OK
2025-10-13 15:40:27,220 - gateway - INFO - Stats - RX: 0, TX: 0, Buffered: 0, Local: OK, VPS: OK
2025-10-13 15:40:47,913 - gateway - INFO - 
Shutting down...
2025-10-13 15:40:47,913 - gateway - INFO - Cleaning up connections...
2025-10-13 15:40:48,451 - gateway - WARNING -  Local MQTT disconnected (rc=0)
2025-10-13 15:40:48,451 - gateway - INFO - Gateway stopped
2025-10-13 15:40:48,451 - gateway - INFO - Cleaning up connections...
2025-10-13 15:40:48,451 - gateway - INFO - Gateway stopped
2025-10-13 15:40:50,169 - gateway - INFO - Setting up Local MQTT Broker...
2025-10-13 15:40:50,389 - gateway - INFO - Setting up VPS MQTT...
2025-10-13 15:40:50,389 - gateway - INFO -  Connected to Local MQTT
2025-10-13 15:40:50,390 - gateway - INFO -  Subscribed to local topics
2025-10-13 15:40:50,393 - gateway - INFO -  VPS mTLS configured
2025-10-13 15:40:55,404 - gateway - ERROR - VPS MQTT connection failed: timed out
2025-10-13 15:40:55,409 - gateway - INFO -  LoRa connected on COM5
2025-10-13 15:40:55,409 - gateway - INFO - ============================================================
2025-10-13 15:40:55,409 - gateway - INFO - Gateway started successfully
2025-10-13 15:40:55,413 - gateway - INFO - Local MQTT: 192.168.1.148:1884
2025-10-13 15:40:55,413 - gateway - INFO - VPS MQTT: 128.199.137.3:8883
2025-10-13 15:40:55,413 - gateway - INFO - ============================================================
2025-10-13 15:41:55,521 - gateway - INFO - Stats - RX: 0, TX: 0, Buffered: 0, Local: OK, VPS: OK
2025-10-13 15:42:55,618 - gateway - INFO - Stats - RX: 0, TX: 0, Buffered: 0, Local: OK, VPS: OK
2025-10-13 15:43:55,628 - gateway - INFO - Stats - RX: 0, TX: 0, Buffered: 0, Local: OK, VPS: OK
2025-10-13 15:44:55,670 - gateway - INFO - Stats - RX: 0, TX: 0, Buffered: 0, Local: OK, VPS: OK
2025-10-13 15:45:55,721 - gateway - INFO - Stats - RX: 0, TX: 0, Buffered: 0, Local: OK, VPS: OK
2025-10-13 15:46:55,794 - gateway - INFO - Stats - RX: 0, TX: 0, Buffered: 0, Local: OK, VPS: OK
2025-10-13 15:47:55,827 - gateway - INFO - Stats - RX: 0, TX: 0, Buffered: 0, Local: OK, VPS: OK
2025-10-13 15:48:55,842 - gateway - INFO - Stats - RX: 0, TX: 0, Buffered: 0, Local: OK, VPS: OK
2025-10-13 15:49:55,863 - gateway - INFO - Stats - RX: 0, TX: 0, Buffered: 0, Local: OK, VPS: OK
2025-10-13 15:50:55,937 - gateway - INFO - Stats - RX: 0, TX: 0, Buffered: 0, Local: OK, VPS: OK
2025-10-13 15:51:55,974 - gateway - INFO - Stats - RX: 0, TX: 0, Buffered: 0, Local: OK, VPS: OK
2025-10-13 15:52:56,014 - gateway - INFO - Stats - RX: 0, TX: 0, Buffered: 0, Local: OK, VPS: OK
2025-10-13 15:53:56,045 - gateway - INFO - Stats - RX: 0, TX: 0, Buffered: 0, Local: OK, VPS: OK
2025-10-13 15:54:56,063 - gateway - INFO - Stats - RX: 0, TX: 0, Buffered: 0, Local: OK, VPS: OK
2025-10-13 15:55:56,101 - gateway - INFO - Stats - RX: 0, TX: 0, Buffered: 0, Local: OK, VPS: OK
2025-10-13 15:56:56,125 - gateway - INFO - Stats - RX: 0, TX: 0, Buffered: 0, Local: OK, VPS: OK
2025-10-13 15:57:56,191 - gateway - INFO - Stats - RX: 0, TX: 0, Buffered: 0, Local: OK, VPS: OK
2025-10-13 15:58:56,272 - gateway - INFO - Stats - RX: 0, TX: 0, Buffered: 0, Local: OK, VPS: OK
2025-10-13 15:59:56,310 - gateway - INFO - Stats - RX: 0, TX: 0, Buffered: 0, Local: OK, VPS: OK
2025-10-13 16:00:56,374 - gateway - INFO - Stats - RX: 0, TX: 0, Buffered: 0, Local: OK, VPS: OK
2025-10-13 16:01:43,459 - gateway - INFO - 
Shutting down...
2025-10-13 16:01:43,459 - gateway - INFO - Cleaning up connections...
2025-10-13 16:01:43,722 - gateway - WARNING -  Local MQTT disconnected (rc=0)
2025-10-13 16:01:43,724 - gateway - INFO - Gateway stopped
2025-10-13 16:01:43,725 - gateway - INFO - Cleaning up connections...
2025-10-13 16:01:43,725 - gateway - INFO - Gateway stopped
2025-10-13 16:05:11,777 - gateway - INFO - Setting up Local MQTT Broker...
2025-10-13 16:05:11,981 - gateway - INFO - Setting up VPS MQTT...
2025-10-13 16:05:11,983 - gateway - INFO -  Connected to Local MQTT
2025-10-13 16:05:11,984 - gateway - INFO -  Subscribed to local topics
2025-10-13 16:05:11,985 - gateway - INFO -  VPS mTLS configured
2025-10-13 16:05:16,987 - gateway - ERROR - VPS MQTT connection failed: timed out
2025-10-13 16:05:17,054 - gateway - INFO -  LoRa connected on COM5
2025-10-13 16:05:17,055 - gateway - INFO - ============================================================
2025-10-13 16:05:17,055 - gateway - INFO - Gateway started successfully
2025-10-13 16:05:17,055 - gateway - INFO - Local MQTT: 192.168.1.148:1884
2025-10-13 16:05:17,056 - gateway - INFO - VPS MQTT: 128.199.137.3:8883
2025-10-13 16:05:17,056 - gateway - INFO - ============================================================
2025-10-13 16:06:17,124 - gateway - INFO - Stats - RX: 0, TX: 0, Buffered: 0, Local: OK, VPS: OK
2025-10-13 16:07:17,205 - gateway - INFO - Stats - RX: 0, TX: 0, Buffered: 0, Local: OK, VPS: OK
2025-10-14 20:55:31,965 - gateway - ERROR - Error setting up local broker (attempt 1): [WinError 10061] No connection could be made because the target machine actively refused it
2025-10-14 20:55:37,353 - gateway - INFO - Local MQTT broker connected successfully
2025-10-14 20:55:37,353 - gateway - INFO - Connected to local MQTT broker
2025-10-14 20:55:38,677 - gateway - INFO - AWS MQTT connected successfully
2025-10-14 20:55:38,745 - gateway - INFO - LoRa connected on COM5
2025-10-14 20:55:38,745 - gateway - INFO - Gateway started
2025-10-14 20:55:39,416 - gateway - INFO - Connected to AWS IoT
2025-10-14 20:56:43,619 - gateway - INFO - Shutting down gateway...
2025-10-14 20:56:43,619 - gateway - INFO - Cleaning up connections...
2025-10-14 20:56:44,121 - gateway - INFO - Gateway stopped
2025-10-14 20:56:50,112 - gateway - INFO - Setting up Local MQTT Broker...
2025-10-14 20:56:50,316 - gateway - INFO - Setting up VPS MQTT...
2025-10-14 20:56:50,316 - gateway - INFO -  Connected to Local MQTT
2025-10-14 20:56:50,318 - gateway - INFO -  Subscribed to local topics
2025-10-14 20:56:50,342 - gateway - INFO -  VPS mTLS configured
2025-10-14 20:56:55,354 - gateway - ERROR - VPS MQTT connection failed: timed out
2025-10-14 20:56:55,423 - gateway - INFO -  LoRa connected on COM5
2025-10-14 20:56:55,423 - gateway - INFO - ============================================================
2025-10-14 20:56:55,423 - gateway - INFO - Gateway started successfully
2025-10-14 20:56:55,423 - gateway - INFO - Local MQTT: 192.168.1.148:1884
2025-10-14 20:56:55,424 - gateway - INFO - VPS MQTT: 128.199.137.3:8883
2025-10-14 20:56:55,424 - gateway - INFO - ============================================================
2025-10-14 20:57:55,455 - gateway - INFO - Stats - RX: 0, TX: 0, Buffered: 0, Local: OK, VPS: OK
2025-10-14 20:58:55,477 - gateway - INFO - Stats - RX: 0, TX: 0, Buffered: 0, Local: OK, VPS: OK
2025-10-14 20:59:55,561 - gateway - INFO - Stats - RX: 0, TX: 0, Buffered: 0, Local: OK, VPS: OK
2025-10-14 21:00:55,599 - gateway - INFO - Stats - RX: 0, TX: 0, Buffered: 0, Local: OK, VPS: OK
2025-10-14 21:01:55,681 - gateway - INFO - Stats - RX: 0, TX: 0, Buffered: 0, Local: OK, VPS: OK
2025-10-14 21:02:55,767 - gateway - INFO - Stats - RX: 0, TX: 0, Buffered: 0, Local: OK, VPS: OK
2025-10-14 21:03:55,767 - gateway - INFO - Stats - RX: 0, TX: 0, Buffered: 0, Local: OK, VPS: OK
2025-10-14 21:04:55,867 - gateway - INFO - Stats - RX: 0, TX: 0, Buffered: 0, Local: OK, VPS: OK
2025-10-14 21:05:55,914 - gateway - INFO - Stats - RX: 0, TX: 0, Buffered: 0, Local: OK, VPS: OK
2025-10-14 21:06:55,950 - gateway - INFO - Stats - RX: 0, TX: 0, Buffered: 0, Local: OK, VPS: OK
2025-10-14 21:07:55,979 - gateway - INFO - Stats - RX: 0, TX: 0, Buffered: 0, Local: OK, VPS: OK
2025-10-14 21:08:56,015 - gateway - INFO - Stats - RX: 0, TX: 0, Buffered: 0, Local: OK, VPS: OK
2025-10-14 21:09:56,047 - gateway - INFO - Stats - RX: 0, TX: 0, Buffered: 0, Local: OK, VPS: OK
2025-10-14 21:10:56,107 - gateway - INFO - Stats - RX: 0, TX: 0, Buffered: 0, Local: OK, VPS: OK
2025-10-14 21:11:56,175 - gateway - INFO - Stats - RX: 0, TX: 0, Buffered: 0, Local: OK, VPS: OK
2025-10-14 21:12:56,276 - gateway - INFO - Stats - RX: 0, TX: 0, Buffered: 0, Local: OK, VPS: OK
2025-10-14 21:13:56,277 - gateway - INFO - Stats - RX: 0, TX: 0, Buffered: 0, Local: OK, VPS: OK
2025-10-14 21:14:56,336 - gateway - INFO - Stats - RX: 0, TX: 0, Buffered: 0, Local: OK, VPS: OK
2025-10-14 21:15:56,413 - gateway - INFO - Stats - RX: 0, TX: 0, Buffered: 0, Local: OK, VPS: OK
2025-10-14 21:16:56,513 - gateway - INFO - Stats - RX: 0, TX: 0, Buffered: 0, Local: OK, VPS: OK
2025-10-14 21:17:02,363 - gateway - INFO - RFID 8675f205: GRANTED
2025-10-14 21:17:02,363 - gateway - INFO - LoRa >> GRANT
2025-10-14 21:17:31,915 - gateway - INFO - RFID 8675f205: GRANTED
2025-10-14 21:17:31,916 - gateway - INFO - LoRa >> GRANT
2025-10-14 21:17:43,298 - gateway - INFO - RFID 8675f205: GRANTED
2025-10-14 21:17:43,299 - gateway - INFO - LoRa >> GRANT
2025-10-14 21:17:49,214 - gateway - ERROR - Gateway error: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
Traceback (most recent call last):
  File "P:\MMT\__IoT\First_IoT\Gateway\vps_main.py", line 863, in run
    if self.serial_conn and self.serial_conn.in_waiting > 0:
  File "D:\Miniconda3\envs\IoT\lib\site-packages\serial\serialwin32.py", line 259, in in_waiting
    raise SerialException("ClearCommError failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
2025-10-14 21:17:50,235 - gateway - ERROR - Gateway error: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
Traceback (most recent call last):
  File "P:\MMT\__IoT\First_IoT\Gateway\vps_main.py", line 863, in run
    if self.serial_conn and self.serial_conn.in_waiting > 0:
  File "D:\Miniconda3\envs\IoT\lib\site-packages\serial\serialwin32.py", line 259, in in_waiting
    raise SerialException("ClearCommError failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
2025-10-14 21:17:51,245 - gateway - ERROR - Gateway error: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
Traceback (most recent call last):
  File "P:\MMT\__IoT\First_IoT\Gateway\vps_main.py", line 863, in run
    if self.serial_conn and self.serial_conn.in_waiting > 0:
  File "D:\Miniconda3\envs\IoT\lib\site-packages\serial\serialwin32.py", line 259, in in_waiting
    raise SerialException("ClearCommError failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
2025-10-14 21:17:52,256 - gateway - ERROR - Gateway error: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
Traceback (most recent call last):
  File "P:\MMT\__IoT\First_IoT\Gateway\vps_main.py", line 863, in run
    if self.serial_conn and self.serial_conn.in_waiting > 0:
  File "D:\Miniconda3\envs\IoT\lib\site-packages\serial\serialwin32.py", line 259, in in_waiting
    raise SerialException("ClearCommError failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
2025-10-14 21:17:53,265 - gateway - ERROR - Gateway error: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
Traceback (most recent call last):
  File "P:\MMT\__IoT\First_IoT\Gateway\vps_main.py", line 863, in run
    if self.serial_conn and self.serial_conn.in_waiting > 0:
  File "D:\Miniconda3\envs\IoT\lib\site-packages\serial\serialwin32.py", line 259, in in_waiting
    raise SerialException("ClearCommError failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
2025-10-14 21:17:54,273 - gateway - ERROR - Gateway error: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
Traceback (most recent call last):
  File "P:\MMT\__IoT\First_IoT\Gateway\vps_main.py", line 863, in run
    if self.serial_conn and self.serial_conn.in_waiting > 0:
  File "D:\Miniconda3\envs\IoT\lib\site-packages\serial\serialwin32.py", line 259, in in_waiting
    raise SerialException("ClearCommError failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
2025-10-14 21:17:55,284 - gateway - ERROR - Gateway error: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
Traceback (most recent call last):
  File "P:\MMT\__IoT\First_IoT\Gateway\vps_main.py", line 863, in run
    if self.serial_conn and self.serial_conn.in_waiting > 0:
  File "D:\Miniconda3\envs\IoT\lib\site-packages\serial\serialwin32.py", line 259, in in_waiting
    raise SerialException("ClearCommError failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
2025-10-14 21:17:56,299 - gateway - ERROR - Gateway error: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
Traceback (most recent call last):
  File "P:\MMT\__IoT\First_IoT\Gateway\vps_main.py", line 863, in run
    if self.serial_conn and self.serial_conn.in_waiting > 0:
  File "D:\Miniconda3\envs\IoT\lib\site-packages\serial\serialwin32.py", line 259, in in_waiting
    raise SerialException("ClearCommError failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
2025-10-14 21:17:57,305 - gateway - INFO - Stats - RX: 0, TX: 0, Buffered: 8, Local: OK, VPS: OK
2025-10-14 21:17:57,306 - gateway - ERROR - Gateway error: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
Traceback (most recent call last):
  File "P:\MMT\__IoT\First_IoT\Gateway\vps_main.py", line 863, in run
    if self.serial_conn and self.serial_conn.in_waiting > 0:
  File "D:\Miniconda3\envs\IoT\lib\site-packages\serial\serialwin32.py", line 259, in in_waiting
    raise SerialException("ClearCommError failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
2025-10-14 21:17:58,314 - gateway - ERROR - Gateway error: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
Traceback (most recent call last):
  File "P:\MMT\__IoT\First_IoT\Gateway\vps_main.py", line 863, in run
    if self.serial_conn and self.serial_conn.in_waiting > 0:
  File "D:\Miniconda3\envs\IoT\lib\site-packages\serial\serialwin32.py", line 259, in in_waiting
    raise SerialException("ClearCommError failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
2025-10-14 21:17:59,328 - gateway - ERROR - Gateway error: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
Traceback (most recent call last):
  File "P:\MMT\__IoT\First_IoT\Gateway\vps_main.py", line 863, in run
    if self.serial_conn and self.serial_conn.in_waiting > 0:
  File "D:\Miniconda3\envs\IoT\lib\site-packages\serial\serialwin32.py", line 259, in in_waiting
    raise SerialException("ClearCommError failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
2025-10-14 21:18:00,329 - gateway - ERROR - Gateway error: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
Traceback (most recent call last):
  File "P:\MMT\__IoT\First_IoT\Gateway\vps_main.py", line 863, in run
    if self.serial_conn and self.serial_conn.in_waiting > 0:
  File "D:\Miniconda3\envs\IoT\lib\site-packages\serial\serialwin32.py", line 259, in in_waiting
    raise SerialException("ClearCommError failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
2025-10-14 21:18:01,340 - gateway - ERROR - Gateway error: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
Traceback (most recent call last):
  File "P:\MMT\__IoT\First_IoT\Gateway\vps_main.py", line 863, in run
    if self.serial_conn and self.serial_conn.in_waiting > 0:
  File "D:\Miniconda3\envs\IoT\lib\site-packages\serial\serialwin32.py", line 259, in in_waiting
    raise SerialException("ClearCommError failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
2025-10-14 21:18:02,345 - gateway - ERROR - Gateway error: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
Traceback (most recent call last):
  File "P:\MMT\__IoT\First_IoT\Gateway\vps_main.py", line 863, in run
    if self.serial_conn and self.serial_conn.in_waiting > 0:
  File "D:\Miniconda3\envs\IoT\lib\site-packages\serial\serialwin32.py", line 259, in in_waiting
    raise SerialException("ClearCommError failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
2025-10-14 21:18:03,353 - gateway - ERROR - Gateway error: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
Traceback (most recent call last):
  File "P:\MMT\__IoT\First_IoT\Gateway\vps_main.py", line 863, in run
    if self.serial_conn and self.serial_conn.in_waiting > 0:
  File "D:\Miniconda3\envs\IoT\lib\site-packages\serial\serialwin32.py", line 259, in in_waiting
    raise SerialException("ClearCommError failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
2025-10-14 21:18:04,374 - gateway - ERROR - Gateway error: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
Traceback (most recent call last):
  File "P:\MMT\__IoT\First_IoT\Gateway\vps_main.py", line 863, in run
    if self.serial_conn and self.serial_conn.in_waiting > 0:
  File "D:\Miniconda3\envs\IoT\lib\site-packages\serial\serialwin32.py", line 259, in in_waiting
    raise SerialException("ClearCommError failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
2025-10-14 21:18:05,382 - gateway - ERROR - Gateway error: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
Traceback (most recent call last):
  File "P:\MMT\__IoT\First_IoT\Gateway\vps_main.py", line 863, in run
    if self.serial_conn and self.serial_conn.in_waiting > 0:
  File "D:\Miniconda3\envs\IoT\lib\site-packages\serial\serialwin32.py", line 259, in in_waiting
    raise SerialException("ClearCommError failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
2025-10-14 21:18:06,397 - gateway - ERROR - Gateway error: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
Traceback (most recent call last):
  File "P:\MMT\__IoT\First_IoT\Gateway\vps_main.py", line 863, in run
    if self.serial_conn and self.serial_conn.in_waiting > 0:
  File "D:\Miniconda3\envs\IoT\lib\site-packages\serial\serialwin32.py", line 259, in in_waiting
    raise SerialException("ClearCommError failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
2025-10-14 21:18:07,410 - gateway - ERROR - Gateway error: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
Traceback (most recent call last):
  File "P:\MMT\__IoT\First_IoT\Gateway\vps_main.py", line 863, in run
    if self.serial_conn and self.serial_conn.in_waiting > 0:
  File "D:\Miniconda3\envs\IoT\lib\site-packages\serial\serialwin32.py", line 259, in in_waiting
    raise SerialException("ClearCommError failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
2025-10-14 21:18:08,415 - gateway - ERROR - Gateway error: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
Traceback (most recent call last):
  File "P:\MMT\__IoT\First_IoT\Gateway\vps_main.py", line 863, in run
    if self.serial_conn and self.serial_conn.in_waiting > 0:
  File "D:\Miniconda3\envs\IoT\lib\site-packages\serial\serialwin32.py", line 259, in in_waiting
    raise SerialException("ClearCommError failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
2025-10-14 21:18:09,429 - gateway - ERROR - Gateway error: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
Traceback (most recent call last):
  File "P:\MMT\__IoT\First_IoT\Gateway\vps_main.py", line 863, in run
    if self.serial_conn and self.serial_conn.in_waiting > 0:
  File "D:\Miniconda3\envs\IoT\lib\site-packages\serial\serialwin32.py", line 259, in in_waiting
    raise SerialException("ClearCommError failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
2025-10-14 21:18:10,444 - gateway - ERROR - Gateway error: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
Traceback (most recent call last):
  File "P:\MMT\__IoT\First_IoT\Gateway\vps_main.py", line 863, in run
    if self.serial_conn and self.serial_conn.in_waiting > 0:
  File "D:\Miniconda3\envs\IoT\lib\site-packages\serial\serialwin32.py", line 259, in in_waiting
    raise SerialException("ClearCommError failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
2025-10-14 21:18:11,452 - gateway - ERROR - Gateway error: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
Traceback (most recent call last):
  File "P:\MMT\__IoT\First_IoT\Gateway\vps_main.py", line 863, in run
    if self.serial_conn and self.serial_conn.in_waiting > 0:
  File "D:\Miniconda3\envs\IoT\lib\site-packages\serial\serialwin32.py", line 259, in in_waiting
    raise SerialException("ClearCommError failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
2025-10-14 21:18:12,461 - gateway - ERROR - Gateway error: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
Traceback (most recent call last):
  File "P:\MMT\__IoT\First_IoT\Gateway\vps_main.py", line 863, in run
    if self.serial_conn and self.serial_conn.in_waiting > 0:
  File "D:\Miniconda3\envs\IoT\lib\site-packages\serial\serialwin32.py", line 259, in in_waiting
    raise SerialException("ClearCommError failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
2025-10-14 21:18:13,461 - gateway - ERROR - Gateway error: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
Traceback (most recent call last):
  File "P:\MMT\__IoT\First_IoT\Gateway\vps_main.py", line 863, in run
    if self.serial_conn and self.serial_conn.in_waiting > 0:
  File "D:\Miniconda3\envs\IoT\lib\site-packages\serial\serialwin32.py", line 259, in in_waiting
    raise SerialException("ClearCommError failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
2025-10-14 21:18:14,483 - gateway - ERROR - Gateway error: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
Traceback (most recent call last):
  File "P:\MMT\__IoT\First_IoT\Gateway\vps_main.py", line 863, in run
    if self.serial_conn and self.serial_conn.in_waiting > 0:
  File "D:\Miniconda3\envs\IoT\lib\site-packages\serial\serialwin32.py", line 259, in in_waiting
    raise SerialException("ClearCommError failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
2025-10-14 21:18:15,486 - gateway - ERROR - Gateway error: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
Traceback (most recent call last):
  File "P:\MMT\__IoT\First_IoT\Gateway\vps_main.py", line 863, in run
    if self.serial_conn and self.serial_conn.in_waiting > 0:
  File "D:\Miniconda3\envs\IoT\lib\site-packages\serial\serialwin32.py", line 259, in in_waiting
    raise SerialException("ClearCommError failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
2025-10-14 21:18:16,498 - gateway - ERROR - Gateway error: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
Traceback (most recent call last):
  File "P:\MMT\__IoT\First_IoT\Gateway\vps_main.py", line 863, in run
    if self.serial_conn and self.serial_conn.in_waiting > 0:
  File "D:\Miniconda3\envs\IoT\lib\site-packages\serial\serialwin32.py", line 259, in in_waiting
    raise SerialException("ClearCommError failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
2025-10-14 21:18:17,509 - gateway - ERROR - Gateway error: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
Traceback (most recent call last):
  File "P:\MMT\__IoT\First_IoT\Gateway\vps_main.py", line 863, in run
    if self.serial_conn and self.serial_conn.in_waiting > 0:
  File "D:\Miniconda3\envs\IoT\lib\site-packages\serial\serialwin32.py", line 259, in in_waiting
    raise SerialException("ClearCommError failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
2025-10-14 21:18:18,518 - gateway - ERROR - Gateway error: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
Traceback (most recent call last):
  File "P:\MMT\__IoT\First_IoT\Gateway\vps_main.py", line 863, in run
    if self.serial_conn and self.serial_conn.in_waiting > 0:
  File "D:\Miniconda3\envs\IoT\lib\site-packages\serial\serialwin32.py", line 259, in in_waiting
    raise SerialException("ClearCommError failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
2025-10-14 21:18:19,529 - gateway - ERROR - Gateway error: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
Traceback (most recent call last):
  File "P:\MMT\__IoT\First_IoT\Gateway\vps_main.py", line 863, in run
    if self.serial_conn and self.serial_conn.in_waiting > 0:
  File "D:\Miniconda3\envs\IoT\lib\site-packages\serial\serialwin32.py", line 259, in in_waiting
    raise SerialException("ClearCommError failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
2025-10-14 21:18:20,532 - gateway - ERROR - Gateway error: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
Traceback (most recent call last):
  File "P:\MMT\__IoT\First_IoT\Gateway\vps_main.py", line 863, in run
    if self.serial_conn and self.serial_conn.in_waiting > 0:
  File "D:\Miniconda3\envs\IoT\lib\site-packages\serial\serialwin32.py", line 259, in in_waiting
    raise SerialException("ClearCommError failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
2025-10-14 21:18:21,537 - gateway - ERROR - Gateway error: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
Traceback (most recent call last):
  File "P:\MMT\__IoT\First_IoT\Gateway\vps_main.py", line 863, in run
    if self.serial_conn and self.serial_conn.in_waiting > 0:
  File "D:\Miniconda3\envs\IoT\lib\site-packages\serial\serialwin32.py", line 259, in in_waiting
    raise SerialException("ClearCommError failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
2025-10-14 21:18:22,544 - gateway - ERROR - Gateway error: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
Traceback (most recent call last):
  File "P:\MMT\__IoT\First_IoT\Gateway\vps_main.py", line 863, in run
    if self.serial_conn and self.serial_conn.in_waiting > 0:
  File "D:\Miniconda3\envs\IoT\lib\site-packages\serial\serialwin32.py", line 259, in in_waiting
    raise SerialException("ClearCommError failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
2025-10-14 21:18:23,554 - gateway - ERROR - Gateway error: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
Traceback (most recent call last):
  File "P:\MMT\__IoT\First_IoT\Gateway\vps_main.py", line 863, in run
    if self.serial_conn and self.serial_conn.in_waiting > 0:
  File "D:\Miniconda3\envs\IoT\lib\site-packages\serial\serialwin32.py", line 259, in in_waiting
    raise SerialException("ClearCommError failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
2025-10-14 21:18:24,561 - gateway - ERROR - Gateway error: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
Traceback (most recent call last):
  File "P:\MMT\__IoT\First_IoT\Gateway\vps_main.py", line 863, in run
    if self.serial_conn and self.serial_conn.in_waiting > 0:
  File "D:\Miniconda3\envs\IoT\lib\site-packages\serial\serialwin32.py", line 259, in in_waiting
    raise SerialException("ClearCommError failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
2025-10-14 21:18:25,583 - gateway - ERROR - Gateway error: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
Traceback (most recent call last):
  File "P:\MMT\__IoT\First_IoT\Gateway\vps_main.py", line 863, in run
    if self.serial_conn and self.serial_conn.in_waiting > 0:
  File "D:\Miniconda3\envs\IoT\lib\site-packages\serial\serialwin32.py", line 259, in in_waiting
    raise SerialException("ClearCommError failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
2025-10-14 21:18:26,596 - gateway - ERROR - Gateway error: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
Traceback (most recent call last):
  File "P:\MMT\__IoT\First_IoT\Gateway\vps_main.py", line 863, in run
    if self.serial_conn and self.serial_conn.in_waiting > 0:
  File "D:\Miniconda3\envs\IoT\lib\site-packages\serial\serialwin32.py", line 259, in in_waiting
    raise SerialException("ClearCommError failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
2025-10-14 21:18:27,607 - gateway - ERROR - Gateway error: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
Traceback (most recent call last):
  File "P:\MMT\__IoT\First_IoT\Gateway\vps_main.py", line 863, in run
    if self.serial_conn and self.serial_conn.in_waiting > 0:
  File "D:\Miniconda3\envs\IoT\lib\site-packages\serial\serialwin32.py", line 259, in in_waiting
    raise SerialException("ClearCommError failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
2025-10-14 21:18:28,614 - gateway - ERROR - Gateway error: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
Traceback (most recent call last):
  File "P:\MMT\__IoT\First_IoT\Gateway\vps_main.py", line 863, in run
    if self.serial_conn and self.serial_conn.in_waiting > 0:
  File "D:\Miniconda3\envs\IoT\lib\site-packages\serial\serialwin32.py", line 259, in in_waiting
    raise SerialException("ClearCommError failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
2025-10-14 21:18:29,629 - gateway - ERROR - Gateway error: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
Traceback (most recent call last):
  File "P:\MMT\__IoT\First_IoT\Gateway\vps_main.py", line 863, in run
    if self.serial_conn and self.serial_conn.in_waiting > 0:
  File "D:\Miniconda3\envs\IoT\lib\site-packages\serial\serialwin32.py", line 259, in in_waiting
    raise SerialException("ClearCommError failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
2025-10-14 21:18:30,629 - gateway - ERROR - Gateway error: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
Traceback (most recent call last):
  File "P:\MMT\__IoT\First_IoT\Gateway\vps_main.py", line 863, in run
    if self.serial_conn and self.serial_conn.in_waiting > 0:
  File "D:\Miniconda3\envs\IoT\lib\site-packages\serial\serialwin32.py", line 259, in in_waiting
    raise SerialException("ClearCommError failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
2025-10-14 21:18:31,633 - gateway - ERROR - Gateway error: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
Traceback (most recent call last):
  File "P:\MMT\__IoT\First_IoT\Gateway\vps_main.py", line 863, in run
    if self.serial_conn and self.serial_conn.in_waiting > 0:
  File "D:\Miniconda3\envs\IoT\lib\site-packages\serial\serialwin32.py", line 259, in in_waiting
    raise SerialException("ClearCommError failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
2025-10-14 21:18:32,636 - gateway - ERROR - Gateway error: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
Traceback (most recent call last):
  File "P:\MMT\__IoT\First_IoT\Gateway\vps_main.py", line 863, in run
    if self.serial_conn and self.serial_conn.in_waiting > 0:
  File "D:\Miniconda3\envs\IoT\lib\site-packages\serial\serialwin32.py", line 259, in in_waiting
    raise SerialException("ClearCommError failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
2025-10-14 21:18:33,648 - gateway - ERROR - Gateway error: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
Traceback (most recent call last):
  File "P:\MMT\__IoT\First_IoT\Gateway\vps_main.py", line 863, in run
    if self.serial_conn and self.serial_conn.in_waiting > 0:
  File "D:\Miniconda3\envs\IoT\lib\site-packages\serial\serialwin32.py", line 259, in in_waiting
    raise SerialException("ClearCommError failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
2025-10-14 21:18:34,661 - gateway - ERROR - Gateway error: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
Traceback (most recent call last):
  File "P:\MMT\__IoT\First_IoT\Gateway\vps_main.py", line 863, in run
    if self.serial_conn and self.serial_conn.in_waiting > 0:
  File "D:\Miniconda3\envs\IoT\lib\site-packages\serial\serialwin32.py", line 259, in in_waiting
    raise SerialException("ClearCommError failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
2025-10-14 21:18:35,678 - gateway - ERROR - Gateway error: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
Traceback (most recent call last):
  File "P:\MMT\__IoT\First_IoT\Gateway\vps_main.py", line 863, in run
    if self.serial_conn and self.serial_conn.in_waiting > 0:
  File "D:\Miniconda3\envs\IoT\lib\site-packages\serial\serialwin32.py", line 259, in in_waiting
    raise SerialException("ClearCommError failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
2025-10-14 21:18:36,690 - gateway - ERROR - Gateway error: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
Traceback (most recent call last):
  File "P:\MMT\__IoT\First_IoT\Gateway\vps_main.py", line 863, in run
    if self.serial_conn and self.serial_conn.in_waiting > 0:
  File "D:\Miniconda3\envs\IoT\lib\site-packages\serial\serialwin32.py", line 259, in in_waiting
    raise SerialException("ClearCommError failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
2025-10-14 21:18:37,698 - gateway - ERROR - Gateway error: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
Traceback (most recent call last):
  File "P:\MMT\__IoT\First_IoT\Gateway\vps_main.py", line 863, in run
    if self.serial_conn and self.serial_conn.in_waiting > 0:
  File "D:\Miniconda3\envs\IoT\lib\site-packages\serial\serialwin32.py", line 259, in in_waiting
    raise SerialException("ClearCommError failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
2025-10-14 21:18:38,705 - gateway - ERROR - Gateway error: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
Traceback (most recent call last):
  File "P:\MMT\__IoT\First_IoT\Gateway\vps_main.py", line 863, in run
    if self.serial_conn and self.serial_conn.in_waiting > 0:
  File "D:\Miniconda3\envs\IoT\lib\site-packages\serial\serialwin32.py", line 259, in in_waiting
    raise SerialException("ClearCommError failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
2025-10-14 21:18:39,708 - gateway - ERROR - Gateway error: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
Traceback (most recent call last):
  File "P:\MMT\__IoT\First_IoT\Gateway\vps_main.py", line 863, in run
    if self.serial_conn and self.serial_conn.in_waiting > 0:
  File "D:\Miniconda3\envs\IoT\lib\site-packages\serial\serialwin32.py", line 259, in in_waiting
    raise SerialException("ClearCommError failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
2025-10-14 21:18:40,714 - gateway - ERROR - Gateway error: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
Traceback (most recent call last):
  File "P:\MMT\__IoT\First_IoT\Gateway\vps_main.py", line 863, in run
    if self.serial_conn and self.serial_conn.in_waiting > 0:
  File "D:\Miniconda3\envs\IoT\lib\site-packages\serial\serialwin32.py", line 259, in in_waiting
    raise SerialException("ClearCommError failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
2025-10-14 21:18:41,720 - gateway - ERROR - Gateway error: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
Traceback (most recent call last):
  File "P:\MMT\__IoT\First_IoT\Gateway\vps_main.py", line 863, in run
    if self.serial_conn and self.serial_conn.in_waiting > 0:
  File "D:\Miniconda3\envs\IoT\lib\site-packages\serial\serialwin32.py", line 259, in in_waiting
    raise SerialException("ClearCommError failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
2025-10-14 21:18:42,724 - gateway - ERROR - Gateway error: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
Traceback (most recent call last):
  File "P:\MMT\__IoT\First_IoT\Gateway\vps_main.py", line 863, in run
    if self.serial_conn and self.serial_conn.in_waiting > 0:
  File "D:\Miniconda3\envs\IoT\lib\site-packages\serial\serialwin32.py", line 259, in in_waiting
    raise SerialException("ClearCommError failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
2025-10-14 21:18:43,730 - gateway - ERROR - Gateway error: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
Traceback (most recent call last):
  File "P:\MMT\__IoT\First_IoT\Gateway\vps_main.py", line 863, in run
    if self.serial_conn and self.serial_conn.in_waiting > 0:
  File "D:\Miniconda3\envs\IoT\lib\site-packages\serial\serialwin32.py", line 259, in in_waiting
    raise SerialException("ClearCommError failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
2025-10-14 21:18:44,737 - gateway - ERROR - Gateway error: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
Traceback (most recent call last):
  File "P:\MMT\__IoT\First_IoT\Gateway\vps_main.py", line 863, in run
    if self.serial_conn and self.serial_conn.in_waiting > 0:
  File "D:\Miniconda3\envs\IoT\lib\site-packages\serial\serialwin32.py", line 259, in in_waiting
    raise SerialException("ClearCommError failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
2025-10-14 21:18:45,741 - gateway - ERROR - Gateway error: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
Traceback (most recent call last):
  File "P:\MMT\__IoT\First_IoT\Gateway\vps_main.py", line 863, in run
    if self.serial_conn and self.serial_conn.in_waiting > 0:
  File "D:\Miniconda3\envs\IoT\lib\site-packages\serial\serialwin32.py", line 259, in in_waiting
    raise SerialException("ClearCommError failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: ClearCommError failed (PermissionError(13, 'Access is denied.', None, 5))
2025-10-14 21:18:45,817 - gateway - INFO - Cleaning up connections...
2025-10-14 21:18:45,894 - gateway - WARNING -  Local MQTT disconnected (rc=0)
2025-10-14 21:18:45,894 - gateway - INFO - Gateway stopped
